name: 'Lerna changed'

description: 'Check if has changed'


outputs:
  is_dirty:
    description: "Have changed state since the last tagged release"
    value: ${{ fromJSON(steps.is-dirty.outputs.LERNA_CHANGED) }}

runs:
  using: "composite"
  steps:
    - name: Lerna changed
      shell: bash
      id: is-dirty
      run: |
        output=$(npx lerna changed || echo "$?")

        if [[ $output -eq 0 ]]
          then
            echo "LERNA_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "LERNA_CHANGED=false" >> $GITHUB_OUTPUT
        fi

    - name: Echo var LERNA_CHANGED
      shell: bash
      run: echo "LERNA_CHANGED -> ${{ steps.is-dirty.outputs.LERNA_CHANGED }}"
