name: 'Lerna changed'

description: 'Check if has changed'


outputs:
  is-dirty:
    description: "Have changed state since the last tagged release"
    value: ${{ steps.is-dirty.outputs.IS_DIRTY }}

runs:
  using: "composite"
  steps:
    - name: Lerna changed check
      shell: bash
      id: is-dirty
      run: |
        npx lerna changed --json
        if [ $? -eq 1 ]
          then
            echo "IS_DIRTY=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "IS_DIRTY=true" >> $GITHUB_OUTPUT
        fi

    - name: Echo
      shell: bash
      run: echo "IS_DIRTY -> ${{ steps.is-dirty.outputs.IS_DIRTY }}"
