name: 'Update package-lock.json files'

description: 'Update package-lock.json files after publish RC or latest version'

inputs:
  commit-message:
    description: 'Commit message when updated package-lock'
    required: false
    default: 'chore: update package-locks.json files [skip ci]'
  token:
    description: 'A Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Sync package-lock's root  level
      shell: bash
      run: npm i --no-audit --no-progress --package-lock-only --lockfile-version 2 --legacy-peer-deps

    - name: Remove the node_modules directory from all packages
      shell: bash
      run: npx lerna clean -y

    - name: Sync package-lock files
      uses: nick-fields/retry@master
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: npx lerna exec --no-private -- npm i --no-audit --no-progress --package-lock-only --lockfile-version 2 --legacy-peer-deps --ignore-scripts

    - name: Root deps don't update correctly on first regeneration
      shell: bash
      run: npm i --no-audit --no-progress --package-lock-only --lockfile-version 2 --legacy-peer-deps

    - name: Extract branch name
      id: branch
      shell: bash
      run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

    - name: Commit & Push package-lock's
      uses: actions-js/push@master
      with:
        github_token: ${{ inputs.token }}
        message: ${{ inputs.commit-message }}
        branch: ${{ steps.branch.outputs.BRANCH }}
        author_name: Salute Frontend Team
        author_email: salute.developers@gmail.com
