name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

env:
  SKIP_PERF: ${{ contains(toJson(github.event.pull_request.labels.*.name), 'skip perf') == 'true' }}

jobs:
  run:
    if: ${{ SKIP_PERF }}
    name: Check Health
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: |
          npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap --since=$(git merge-base --fork-point origin/dev)

      - name: Lint
        run: npm run lint
