name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Check Health
    if: ${{ !startsWith(github.head_ref, 'release') }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use state
        id: state
        uses: actions/github-script@v7
        with:
          debug: true
          script: |
            const {
              issue: { number },
              repo: { owner, repo }
            } = context;
            
            console.log(number);
            
            console.log(context);

  context:
    uses: ./.github/workflows/reuse.yml
    secrets: inherit
