name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Check Health
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: |
          npm ci --no-audit
          echo "${{ github.event.pull_request.labels }}"
          echo "${{ contains(github.event.issue.labels.*.name, 'skip perf') }}"

      - name: Lerna bootstrap
        run: npx lerna bootstrap --since=$(git merge-base --fork-point origin/dev)

      - name: Lint
        run: npm run lint
