name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Check Health
    runs-on: ubuntu-latest
    env:
      RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      STATUS_URL: "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Lint
        run: |
          npm run lint
          echo "Job name is $GITHUB_JOB"
          echo "How about ${{ github.jobs[github.job].name }}"

      - name: Set commit status "success"
        run: |
          res=$(curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            ${{ env.STATUS_URL }} \
            -d '{"state":"success","target_url":"${{ env.RUN_URL }}","description":"${{github.jobs[github.job].name}}: Successful", }') || exit 1
          echo $res
          if [[ $res != *"success"* ]]; then
            exit 1
          fi
