name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

env:
  RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  STATUS_URL: "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
jobs:
  run:
    name: Check Health
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Lint
        id: lint
        run: |
          npm run lint

      - name: Set commit status "success"
        run: |
          step_nr=$(echo '${{ toJson(steps) }}' | jq -n)
          echo "$step_nr"
          res=$(curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            ${{ env.STATUS_URL }} \
            -d '{"state":"success","target_url":"${{ env.RUN_URL }}","description": " 2 ": Successful", }') || exit 1
          echo $res
          if [[ $res != *"success"* ]]; then
            exit 1
          fi

  catch:
    name: Catch errors
    runs-on: ubuntu-latest
    needs: run
    if: ${{ always() && contains(needs.*.result, 'failure') }}

    steps:
      - name: Set commit status "failure"
        run: |
          echo "${GITHUB_RUN_ID}"
          echo "${GITHUB_RUN_ID}"
          echo "${GITHUB_JOB}"

      - name: Get jobs information
        id: job
        uses: actions/github-script@v6
        env:
          GITHUB_RUN_ID: ${{ GITHUB_RUN_ID }}
        with:
          script: |
            const { GITHUB_RUN_ID } = process.env;
            
            const jobsList = await github.rest.repos.listJobsForWorkflowRun({
              run_id: GITHUB_RUN_ID,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }) || [];

            // TODO: Input name job for FIND
            const currentJob = jobsList.find(({ name }) => name === "Check Health")
            const failureStep = currentJob.steps.filter(({ conclusion }) => conclusion === "failure" )
            console.log("Failure step name: ", failureStep?.name)
          
