name: Check

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Check Health
    if: ${{ !startsWith(github.head_ref, 'release') }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Lint
        run: |
          npm run lint
