name: Run only by components change

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'packages/**/src/components/**/*.tsx'

jobs:
  poc-reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Huraj"
