name: POC Trigger Target Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: current

      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: dev
          show-progress: false
          path: plasma

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'plasma/.nvmrc'

      - name: Generate android icons
        run: |
          cd plasma/packages/plasma-icons
          nvm use
          npm i
          npm run generate:android

      - name: Mv to dir
        run: |
          cp -r plasma/packages/plasma-icons/android-icons/. current/android-icons/
          ls current/android-icons
          
          
