name: POC Trigger workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Check" ]
    branches: [ dev ]
    types:
      - completed

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Dumb
        env:
          DATA: ${{ toJSON(github.event) }}
        run: |
          echo "$DATA"     

      - name: Get release info
        run: |
          echo "${{ github.event.workflow_run.head_commit.message }}"

  generate:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.android-icons.outputs.artifact-url }}
    steps:
      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: ${{ fromJSON(github.event.client_payload).ref || dev }}
          show-progress: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Bootstrap web
        run: npm ci

      - name: Generate android icons
        run: |
          npx lerna bootstrap --ignore-scripts --scope="@salutejs/plasma-icons" 
          npm run generate:android --prefix="packages/plasma-icons"

      - name: Save android icons
        id: android-icons
        uses: actions/upload-artifact@v4.1.0
        with:
          name: android-icons-${{ fromJSON(github.event.client_payload).ref || dev }}.zip
          path: packages/plasma-icons/archives/android-icons.zip

  download:
    needs: [generate]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Download android icons
        uses: actions/download-artifact@v4.1.0
        with:
          name: android-icons.zip


