name: POC Trigger Target Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: current

      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: Yakutoc/plasma-dev-stage
          ref: dev
          show-progress: false
          path: web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'web/.nvmrc'
          cache: 'npm'

      - name: Generate android icons
        run: |
          cd web/packages/plasma-icons
          ls
          npm ci
          npm run generate:android
          ls android-icons
          
