name: POC Trigger Target Workflow

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          path: current

      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: dev
          show-progress: false
          path: web

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'web/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Bootstrap web
        run: |
          cd web
          npm ci
          npm ci --prefix="web/packages/plasma-icons"
          npm run generate:android --prefix="web/packages/plasma-icons"
