name: Create release PR

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release-notes:
    name: Build Changelog
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Computed envs
        run: |
          echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
          echo "FROM_TAG=$(git merge-base --fork-point origin/main)" >> $GITHUB_ENV

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## Components",
                  "labels": ["components"]
                },
                {
                  "title": "## Uncategorized",
                  "labels": []
                }
              ],
              "pr_template": "##{{BODY}}\n\n #{{TITLE}} (#{{URL}})\n\n"
            }
        env:
          GITHUB_TOKEN: ${{  secrets.GH_TOKEN }}

      - name: Create PR
        run: |
          gh pr create --base main --head dev --title "Release by ${{ env.DATE }}" --body '## Release Notes
          ${{ steps.github_release.outputs.changelog }}'

      - name: Create release changelog md file
        run: |
          tr -d '\r' < echo ${{ steps.github_release.outputs.changelog }} > /home/runner/work/plasma-sandbox/plasma-sandbox/changelog_artifacts.md

      - name: Upload release changelog md
        uses: actions/upload-artifact@master
        with:
          name: Release-changelog-artifacts
          path: /home/runner/work/plasma-sandbox/plasma-sandbox/changelog_artifacts.md
