name: Create release PR

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release-notes:
    name: Build Changelog
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Computed envs
        run: |
          echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
          echo "FROM_TAG=$(git merge-base --fork-point origin/main)" >> $GITHUB_ENV
          echo "SHA - ${{ github.sha }}"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
          toTag: ${{ github.sha }}
          configuration: "./.github/workflows/changelog-builder-config.json"

      - name: Create "changelog_artifacts.md"
        run: |
          cat > ${{ github.workspace }}/changelog_artifacts.md << EOL
          `${{ steps.github_release.outputs.changelog }}`
          EOL    

      - name: ECHO I
        run: |
          echo -i 's|(<img [^>]*[^/])>|\1/>|' < echo `${{ steps.github_release.outputs.changelog }}`

      - name: Cat
        run: |
          sed -E 's|(<img [^>]*[^/])>|\1/>|' ${{ github.workspace }}/changelog_artifacts.md > ${{ github.workspace }}/changelog_artifacts.md
          
