name: Create release PR

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release-notes:
    name: Build Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: |
          npm ci --no-audit
          echo "FROM_TAG=$(git merge-base --fork-point origin/main)" >> $GITHUB_ENV

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
          configurationJson: |
            {
              "pr_template": "- #{{TITLE}}\n PR: ##{{URL}}\n ##{{BODY}}\n ----"
            }
        env:
          GITHUB_TOKEN: ${{  secrets.GH_TOKEN }}

      - name: Changelog
        run: echo "${{ steps.github_release.outputs.changelog }}"
