name: Create release PR

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release-notes:
    name: Build Changelog
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Computed envs
        run: |
          echo "DATE=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
          echo "FROM_TAG=$(git merge-base --fork-point origin/main)" >> $GITHUB_ENV
          echo "FILE_PATH=${{ github.workspace }}/changelog_artifacts.md" >> $GITHUB_ENV
          echo "REF_NAME - ${{github.ref_name}}"
          echo "HEAD_REF - ${{ toJSON(github.event) }}"
          

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
          toTag: ${{ github.sha }}
          configuration: "./.github/workflows/changelog-builder-config.json"

      - name: Create "changelog_artifacts.md"
        run: |
          cat > ${{ env.FILE_PATH }} <<'EOF'
          ${{ steps.github_release.outputs.changelog }}

      - name: Lint
        run: |
          sed -i -E 's|(<img [^>]*[^/])>|\1/>|' ${{ env.FILE_PATH }}

      - name: Upload "changelog_artifacts.md"
        uses: actions/upload-artifact@master
        with:
          name: release-changelog-artifacts
          path: ${{ env.FILE_PATH }}

      - name: Create release PR
        run: |
          body="# Release Notes
          $(cat ${{ env.FILE_PATH }})"
          gh pr create --base main --head ${{ github.ref_name }} --title "Release by ${{ env.DATE }}" --body "$body"
          git reset --hard
          
