name: POC Install Icons Pack

on:
  pull_request:
  workflow_dispatch:
    inputs:
      plasma-ref:
        required: true
        description: ''
        default: master
      plasma-version:
        description: ''
        required: true

jobs:
  icons:
    runs-on: macos-latest
    environment: sdds

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0
          path: current

      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: feat-icons-png-generator
          show-progress: false
          path: plasma

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'plasma/.nvmrc'

      - name: Install plasma web project deps
        working-directory: ./plasma
        run: npm ci

      - name: Generate iOS icons
        working-directory: ./plasma
        run: |
          npx lerna bootstrap --scope="@salutejs/plasma-icons" 
          npm run generate:ios --prefix="packages/plasma-icons"

      - name: ls
        working-directory: ./plasma
        run: |
          cd packages/plasma-icons
          ls icons-ios
