name: Pre-publish

on:
  merge_group:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Publish check
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Release Info
        run: npm whoami && npx lerna info && npx auto info || echo 'auto info returned 1'

      - name: Create Pre-Release
        run: npm run release --dry-run
