name: Publish Canary

on:
  pull_request_target:
    branches: [dev]

jobs:
  authorize:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    steps:
      - run: "External pull request, (from fork) approved by code owners"

  publish:
    name: Publish RC version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
