name: Publish RC

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  publish:
    name: Publish RC version
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      commit-message: "chore: update package-locks"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
