name: Publish Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Release
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      upload_assets: true
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}

