name: Publish Canary

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  release:
    name: Publish Canary
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unset header
        # https://github.com/intuit/auto/issues/1030
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna found changed packages
        run: |
          lerna=$(npx lerna changed || echo "$?")
          if [[ $lerna -eq 1 ]]
            then
              echo "LERNA_NO_CHANGED=true" >> $GITHUB_ENV
            else
              echo "LERNA_NO_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: test
        run: |
          echo "var -> ${{ env.LERNA_NO_CHANGED }}"
