name: Publish Canary

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  publish:
    name: Publish RC version
    uses: ./.github/workflows/publish-common.yml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
