name: Publish Canary

on:
  pull_request_target:
    branches: [dev]

# Enabled permissions on GITHUB_TOKEN
permissions:
  # To be able to push to the repo
  contents: write
  # To update the pr description with canary info
  pull-requests: write
  # For pr-check to create a status
  statuses: write
  # Needed to create PR statuses/checks
  checks: write
  # To post comments on PRs
  issues: write

jobs:
  authorize:
    runs-on: ubuntu-latest
    ## Possible value external
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    steps:
      - name: Echo
        run: |
          echo "External pull request approved by code owners"

      - name: Echo
        run: |
          echo "2 => ${{ github.event.pull_request.head.repo.full_name }}"
          echo "3 => ${{ github.repository }}"

  publish:
    name: Publish RC version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
