name: Publish Canary

on:
  pull_request_target:
    branches: [dev]

jobs:
  authorize:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    steps:
      - name: Echo
        run: "External pull request, (from fork) approved by code owners"
      - name: Echo
        run: |
          echo "1 => ${{ github.event_name == 'pull_request_target' }}"
          echo "2 => ${{ github.event.pull_request.head.repo.full_name }}"
          echo "3 => ${{ github.repository }}"
          echo "4 => ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}"

  publish:
    name: Publish RC version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
