name: Publish Canary

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  release:
    name: Publish Canary
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_REGISTRY_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unset header
        # https://github.com/intuit/auto/issues/1030
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna found changed packages
        id: is-changed
        uses: ./.github/actions/lerna-changed

      - name: Create "IS_CHANGED" shortcut
        run: echo "IS_CHANGED=${{ steps.is-changed.outputs.is-changed }}" >> $GITHUB_ENV

      - name: Lerna bootstrap
        if: ${{ fromJSON(env.IS_CHANGED) }}
        run: npx lerna bootstrap

      - name: Release Info
        if: ${{ success() }}
        run: npm whoami && npx lerna info && npx auto info || echo 'auto info returned 1'

      - name: Create Release
        if: ${{ success() }}
        run: npm run release
