name: Publish RC

on:
  pull_request_target:
    types: [closed]

jobs:
  publish:
    name: Publish RC version
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      commit-message: "chore: update package-locks"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
