name: Check

on:
  pull_request:
    branches:
      - 'release_**'

jobs:
  run:
    name: Check Health
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: |
          echo "REF_NAME => ${{ github.ref_name }}"
