name: Pull request release into master

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    if: ${{ startsWith(github.head_ref, 'release') }}

    name: Pull request release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: |
          echo "REF_NAME => ${{ github.ref_name }}"
