name: Pull request release

on:
  pull_request:
    branches:
      - 'release'

jobs:
  run:
    name: Pull request release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: |
          echo "REF_NAME => ${{ github.ref_name }}"
