name: Status

on:
  status:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ github.event.state }}"
          echo "${{ github.event.context }}"
          echo The status is error or failed: $DESCRIPTION
          
      - name: Create the Mattermost Message
        run: |
          echo "{\"text\":\" ${{github.event.description}}\"}" > mattermost.json

      - name: Send notification
        uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOKS_NOTIFICATIONS_MM }}
