name: Check run state

on:
  check_run:
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo "${{ github.event }}"
          echo The status is error or failed: $DESCRIPTION
