name: Status

on:
  status:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo "${{ fromJSON(github.event) }}"
          echo "${{ github.event.state }}"
          echo "${{ github.event.context }}"
          echo The status is error or failed: $DESCRIPTION
