name: Status

on:
  status:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo "${{ env.GITHUB_CONTEXT }}"
          echo "${{ github.event.state }}"
          echo "${{ github.event.context }}"
          echo The status is error or failed: $DESCRIPTION
