name: Subscribe to custom event

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-icons]

jobs:
  plasma-icons:
    runs-on: ubuntu-latest
    outputs:
      FILE_NAME: ${{ steps.file.outputs.FILE_NAME }}
    steps:
      - name: Checkout to Plasma Web
        uses: actions/checkout@v4
        with:
          repository: salute-developers/plasma
          ref: ${{ github.event.client_payload.ref || 'dev' }}
          show-progress: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Bootstrap web project
        run: npm ci

      - name: Create file name
        run: |
          echo "FILE_NAME=android-icons-${{ github.event.client_payload.version }}.zip" >> "$GITHUB_ENV"

      - name: Create file name
        id: file
        run: |
          echo "FILE_NAME=${{ env.FILE_NAME }}" >> "$GITHUB_OUTPUT"     

      - name: Generate android icons
        run: |
          npx lerna bootstrap --ignore-scripts --scope="@salutejs/plasma-icons" 
          npm run generate:android --prefix="packages/plasma-icons"

      - name: Save android icons
        uses: actions/upload-artifact@v4.1.0
        with:
          name: android-icons-${{ github.event.client_payload.version }}.zip
          path: packages/plasma-icons/archives/android-icons.zip

  download:
    needs: [plasma-icons]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.plasma-icons.outputs.FILE_NAME }}

      - name: LS echo
        run: |
          ls -lh
