name: Sync package-lock.json files

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        shell: bash
        run: npm ci
        
      - name: Update package-lock files
        uses: ./.github/actions/update-package-lock
        with:
          commit-message: 'chore: update package-locks [skip ci]'
          token: ${{ secrets.GH_TOKEN }}
