name: Get pull request info

on:
  workflow_dispatch:

jobs:
  pull-r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: WIP
        id: p
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            
            const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log(res);
