name: Get pull request info

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: listPullRequestsAssociatedWithCommit
        id: pr_state
        uses: actions/github-script@v6
        with:
          script: | 
            const teammate = {
              Yakutoc: "alex_czech",
              'neretin-trike': "aaneretin",
              'Yeti-or': "yeti-or",
              TitanKuzmich: "aakrivonos",
              kayman233: "ivakudryavtsev",
            };
            
            const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: '0be4654a770b02531948d59e5c326a07101135f4',
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const { base: { sha = context.sha }, title, user: { login } } = res?.data[0] || {};
            
            return { sha, pr: title, user: teammate[login] };

      - name: Create message
        env:
          PR: ${{ fromJSON(steps.pr_state.outputs.result).pr }}
          USER: ${{ fromJSON(steps.pr_state.outputs.result).user }}
        run: |
          pr="**Publish RC**: ${{ env.PR }}"
          step="**Failure step**: 'Failure'"
          job="**Job**: 'Failure'"
          message="@${{ env.USER }} Посмотри пожалуйста упала публикация"

          echo "NOTIFICATION="$pr\\n$status\\n$step\\n$job\\n$message"" >> $GITHUB_ENV

      - name: Create the Mattermost Message
        run: |
          echo "{\"text\":\"${{ env.NOTIFICATION }}\"}" > mattermost.json

      - name: Send notification
        uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOKS_NOTIFICATIONS_MM }}
