name: Sharing data

on:
  workflow_dispatch:

jobs:
  write_state:
    uses: ./.github/workflows/reuse.yml
    secrets: inherit

  read_state:
    runs-on: ubuntu-latest
    needs:
      - write_state

    steps:
      - uses: actions/checkout@v4
      - name: ECHO
        if: ${{ fromJSON(needs.write_state.outputs.STATE).HAS_SCOPE == true }}
        run: |
          echo "Echo run bla-bla-bla"

      - name: Use state
        id: state
        uses: actions/github-script@v6
        env:
          PACKAGES_STORYBOOK: ${{ vars.PACKAGES_STORYBOOK }}
          OUTPUT: ${{ toJSON(fromJSON(needs.write_state.outputs.STATE).PACKAGES) }}
        with:
          debug: true
          script: |
            const read = require('./.github/read.js');
            
            const {
              issue: { number },
              repo: { owner, repo }
            } = context;
            
            console.log(number);
            
            console.log(context);
            
            return read();    
