name: Sharing data

on:
  workflow_dispatch:

jobs:
  write_state:
    uses: ./.github/workflows/reuse.yml
    secrets: inherit

  read_state:
    runs-on: ubuntu-latest
    needs:
      - write_state

    steps:
      - uses: actions/checkout@v4
      - name: ECHO
        if: ${{ fromJSON(needs.write_state.outputs.STATE).HAS_SCOPE == true }}
        run: |
          echo "Echo run bla-bla-bla"
          

      - name: ECHO
        run: |
          echo "PACKAGES_STORYBOOK=${{ fromJSON(needs.write_state.outputs.STATE).PACKAGES_STORYBOOK }}" >> $GITHUB_ENV
          echo "PACKAGES=${{ fromJSON(needs.write_state.outputs.STATE).PACKAGES }}" >> $GITHUB_ENV

      - name: Use state
        id: state
        uses: actions/github-script@v6
        env:
          PACKAGES_STORYBOOK: ${{ env.PACKAGES_STORYBOOK }}
          PACKAGES: ${{ env.PACKAGES }}
        with:
          script: |
            const read = require('./.github/read.js');
            
            return read();    
