name: Sharing data

on:
  workflow_dispatch:

jobs:
  write_state:
    runs-on: ubuntu-latest
    outputs:
      STATE: ${{ steps.output.outputs.STATE }}
    steps:
      - name: TEST
        id: state
        uses: actions/github-script@v6
        with:
          script: | 
            return {         
              HAS_SCOPE: false,
              HAS_DOCUMENTATION_CHANGED: false,
            }

      - name: Set "GITHUB_OUTPUT"
        id: output
        run: |
          echo "STATE=${{ steps.state.outputs.result }}" >> $GITHUB_OUTPUT

  read_state:
    runs-on: ubuntu-latest
    needs:
      - write_state

    steps:
      - name: ECHO
        if: ${{ fromJSON(needs.write_state.outputs.STATE).HAS_SCOPE == true }}
        run: |
          echo "Echo run bla-bla-bla"
