name: Sharing data

on:
  workflow_dispatch:

jobs:
  write_state:
    uses: ./.github/workflows/reuse.yml
    secrets: inherit

  read_state:
    runs-on: ubuntu-latest
    needs: [write_state]
    env:
      PACKAGES: ${{ toJSON(fromJSON(needs.write_state.outputs.STATE).PACKAGES) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set ENVs
        run: |
          echo "HAS_PACKAGE_DOCS=$([ -d "./utils/pack" ] && echo true || echo false)" >> $GITHUB_ENV   
          echo "NOT_PACKAGE_DOCS=$([ -d "./utils/sssss" ] && echo true || echo false)" >> $GITHUB_ENV   

      - name: ECHO
        if: ${{ fromJSON(env.HAS_PACKAGE_DOCS) }}
        run: |
          echo "Echo HAS"

      - name: ECHO 2
        if: ${{ fromJSON(env.NOT_PACKAGE_DOCS) }}
        run: |
          echo "Echo NOT"        
          echo ${{ env.HAS_PACKAGE_DOCS }}       

      - name: Use state
        id: state
        uses: actions/github-script@v7
        env:
          PACKAGES_STORYBOOK: ${{ toJSON(vars.PACKAGES_STORYBOOK) }}
          OUTPUT: ${{ env.PACKAGES }}
        with:
          debug: true
          script: |
            const read = require('./.github/read.js');
            
            const {
              issue: { number },
              repo: { owner, repo }
            } = context;
          
            console.log(context);
            
            return read();

  run_reuse:
    needs: [read_state]
    uses: ./.github/workflows/reuse.yml
    with:
     s3-bucket: 'secccccc'
    secrets: inherit
