name: POC workflow run

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Sharing data]
    types: [completed]

jobs:
  poc-workflow-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reuse.yml
    secrets: inherit
